language: c
addons:
    apt:
        packages:
            - gcc-avr
            - avr-libc
            - doxygen
notifications:
    email: false

install: true

env:
    - PRESCALER=1024 TIMERBITS=16 TIMERNR=0
    - PRESCALER=1024 TIMERBITS=8 TIMERNR=0
    - PRESCALER=256 TIMERBITS=16 TIMERNR=1
    - PRESCALER=64 TIMERBITS=16 TIMERNR=2
    - PRESCALER=8 TIMERBITS=16 TIMERNR=1
    - PRESCALER=1 TIMERBITS=16 TIMERNR=2

before_script:
    make test PRESCALER=$PRESCALER TIMERNR=$TIMERNR TIMERBITS=$TIMERBITS

script:
    make PRESCALER=$PRESCALER TIMERNR=$TIMERNR TIMERBITS=$TIMERBITS

before_deploy:
    doxygen

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/html
  target-branch: gh-pages
  on:
    branch: master
