language: c
addons:
    apt:
        packages:
            - gcc-avr
            - avr-libc
            - doxygen
install: true

before_script:
    make test

script:
    make

before_deploy:
    doxygen

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/html
  target-branch: gh-pages
  on:
    branch: master
